name: reflex
description: The largest entertainment community on the internet
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.0
  get: ^4.1.2
  image_picker:
  localstorage: ^4.0.0+1
  line_icons: ^2.0.1
  syncfusion_flutter_datepicker: ^18.4.49-beta
  find_dropdown: ^1.0.0
  get_storage: ^2.0.2
  extended_image: ^4.0.1
  flutter_colorpicker: ^0.4.0
  # pinput: ^1.2.0
  image_gallery_saver: '^1.6.9'
  # dio: ^4.0.0
  # permission_handler: ^7.0.0
  firebase_messaging:
  flutter_local_notifications:
  http:
  encrypt: ^5.0.0
  file_picker: ^3.0.1
  # flutter_advanced_networkimage: ^0.7.0
  # audioplayers: ^0.18.3
  just_audio: ^0.7.4
  # dependency_overrides:
  # flutter_svg: ^0.18.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: primaryFont
      fonts:
        - asset: fonts/Helvetica.ttf
    - family: primaryBold
      fonts:
        - asset: fonts/HelveticaMedium.ttf